"""
neo4j_exporter.py
~~~~~~~~~~~~~~~~~
Generates Cypher statements that write the garment topology graph into Neo4j.

This module is OPTIONAL — the BFS worker works without Neo4j installed.
Use the Cypher output for offline graph visualisation or batch imports.

Node model
----------
  (:Component:GarmentPart { componentId, name, category, panelRole, ... })

Relationship model
------------------
  (:Component)-[:SEAM { seamId, seamType, seamLengthMm, ... }]->(:Component)

The garment_label parameter lets you tag all nodes with a user-defined label
so multiple DSL runs can coexist in the same Neo4j instance:

    (:Component:TShirtDesign_v1)

Usage
-----
    from neo4j_exporter import export_cypher
    from graph_builder import build_graph, BuildResult

    build_result: BuildResult = build_graph(dsl)
    cypher_text = export_cypher(build_result.graph, garment_label="MyDesign")
    Path("garment.cypher").write_text(cypher_text)

    # Load into Neo4j:
    #   cypher-shell -u neo4j -p <password> < garment.cypher
"""
from __future__ import annotations

import json
from typing import Any

import networkx as nx


# ─────────────────────────────────────────────────────────────────────────────
# Cypher literal helpers
# ─────────────────────────────────────────────────────────────────────────────

def _cypher_str(value: Any) -> str:
    """Render a Python value as a Cypher literal string."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    # dict / list → JSON string property
    return "'" + json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("'", "\\'") + "'"


def _props_map(attrs: dict[str, Any]) -> str:
    """Render a dict as a Cypher map literal: {key: value, ...}"""
    if not attrs:
        return "{}"
    pairs = ", ".join(
        f"{k}: {_cypher_str(v)}"
        for k, v in sorted(attrs.items())
        if v is not None
    )
    return "{" + pairs + "}"


# ─────────────────────────────────────────────────────────────────────────────
# Main export function
# ─────────────────────────────────────────────────────────────────────────────

def export_cypher(graph: nx.Graph, garment_label: str = "GarmentPart") -> str:
    """
    Generate a Cypher script (as a string) to MERGE nodes and SEAM
    relationships from *graph* into Neo4j.

    Parameters
    ----------
    graph:
        NetworkX Graph built by graph_builder.build_graph().
    garment_label:
        Additional node label applied to all component nodes.
        Useful for namespacing multiple design runs in one Neo4j instance.

    Returns
    -------
    str
        Cypher statements separated by newlines; each ends with a semicolon.
    """
    lines: list[str] = [
        "// ── Garment Design Topology Export ──────────────────────────────────",
        f"// garment_label : {garment_label}",
        "// generated by  : bfs_topology_worker.neo4j_exporter",
        "",
        "// ── Component nodes ─────────────────────────────────────────────────",
    ]

    for node_id in sorted(graph.nodes()):
        raw_attrs = dict(graph.nodes[node_id])
        flat: dict[str, Any] = {"componentId": node_id}
        for k, v in raw_attrs.items():
            # Flatten nested dicts/lists to JSON strings for Neo4j property compatibility
            if isinstance(v, (dict, list)):
                flat[k] = json.dumps(v, ensure_ascii=False, separators=(",", ":"))
            else:
                flat[k] = v

        lines.append(
            f"MERGE (n:Component:{garment_label} {{componentId: '{node_id}'}}) "
            f"SET n += {_props_map(flat)};"
        )

    lines.append("")
    lines.append("// ── SEAM relationships ───────────────────────────────────────────────")

    seen_edges: set[frozenset[str]] = set()
    for u, v, data in sorted(graph.edges(data=True), key=lambda e: e[2].get("seamId", f"{e[0]}__{e[1]}")):
        if u == v:
            continue  # skip self-loops — they cannot be expressed as directed SEAM
        edge_key = frozenset({u, v})
        if edge_key in seen_edges:
            continue  # NetworkX Graph is undirected; avoid duplicate directions
        seen_edges.add(edge_key)

        seam_id = data.get("seamId", f"{u}__{v}")
        rel_attrs: dict[str, Any] = {"seamId": seam_id}
        for k, val in data.items():
            if k == "seamId":
                continue
            rel_attrs[k] = json.dumps(val, ensure_ascii=False, separators=(",", ":")) if isinstance(val, (dict, list)) else val

        lines.append(
            f"MATCH (a:Component:{garment_label} {{componentId: '{u}'}}), "
            f"(b:Component:{garment_label} {{componentId: '{v}'}}) "
            f"MERGE (a)-[r:SEAM {{seamId: '{seam_id}'}}]->(b) "
            f"SET r += {_props_map(rel_attrs)};"
        )

    lines.append("")
    return "\n".join(lines)
