"""
drift_code_worker/worker.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Drift Code Generation Worker — AsyncAIFlow action type: drift_code

This worker:
  1. Registers with the AsyncAIFlow runtime.
  2. Polls for drift_code actions.
  3. Reads issue_text (and optionally search_results) from the payload.
  4. Calls OpenAI/GLM to produce a unified-diff patch for the Drift backend.
  5. Writes the patch to tmp/drift_patches/<actionId>.patch.
  6. Submits the patch content as the action result.

Environment variables
---------------------
  ASYNCAIFLOW_SERVER_BASE_URL       = http://localhost:8080
  ASYNCAIFLOW_WORKER_ID             = drift-code-worker-py
  ASYNCAIFLOW_CAPABILITIES          = drift_code
  ASYNCAIFLOW_POLL_INTERVAL_SECONDS = 1.0
  OPENAI_API_KEY                    — OpenAI key (required unless GLM_API_KEY set)
  GLM_API_KEY                       — ZhipuAI GLM-4 key (fallback)
  DRIFT_REPO_PATH                   = .  (root of Drift backend repo)
  DRIFT_PATCH_DIR                   = tmp/drift_patches
"""
from __future__ import annotations

import json
import logging
import os
import pathlib
import time
from typing import Any

ACTION_TYPE = "drift_code"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("drift-code-worker")

# ─────────────────────────────────────────────────────────────────────────────
# LLM helpers
# ─────────────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are an expert Python backend developer working on the Drift game server.
Given an engineering issue, produce a minimal unified-diff patch (git diff format) that resolves it.
Output ONLY the raw patch — no markdown fences, no explanations.
The patch must apply cleanly with `git apply --3way`.
"""


def _call_openai(issue: str, search_results: str) -> str:
    import openai  # type: ignore
    base_url = os.environ.get("OPENAI_BASE_URL") or None
    client = openai.OpenAI(
        api_key=os.environ["OPENAI_API_KEY"],
        base_url=base_url,
    )
    user_msg = f"Issue:\n{issue}"
    if search_results:
        user_msg += f"\n\nRelevant context from codebase:\n{search_results}"
    resp = client.chat.completions.create(
        model=os.environ.get("OPENAI_MODEL", "gpt-4o"),
        temperature=0.2,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
    )
    return resp.choices[0].message.content.strip()


def _call_glm(issue: str, search_results: str) -> str:
    from zhipuai import ZhipuAI  # type: ignore
    base_url = os.environ.get("GLM_BASE_URL") or None
    client = ZhipuAI(
        api_key=os.environ["GLM_API_KEY"],
        base_url=base_url,
    )
    user_msg = f"Issue:\n{issue}"
    if search_results:
        user_msg += f"\n\nRelevant context from codebase:\n{search_results}"
    resp = client.chat.completions.create(
        model=os.environ.get(
            "GLM_MODEL",
            "codegeex-4" if base_url and "coding" in base_url else "glm-4",
        ),
        temperature=0.2,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
    )
    return resp.choices[0].message.content.strip()


def _generate_patch(issue: str, search_results: str) -> str:
    """Try OpenAI first; fall back to GLM; stub in demo mode when no key set."""
    if os.environ.get("GLM_API_KEY"):
        return _call_glm(issue, search_results)
    if os.environ.get("OPENAI_API_KEY"):
        return _call_openai(issue, search_results)
    # Demo/hackathon stub: no LLM key available, return synthetic patch
    import logging as _lg
    _lg.getLogger("drift-code-worker").warning(
        "No LLM API key set — returning stub patch for demo mode"
    )
    return (
        "--- a/drift_patch.py\n"
        "+++ b/drift_patch.py\n"
        "@@ -0,0 +1,3 @@\n"
        "+# Demo stub patch generated by drift_code_worker\n"
        f"+# Issue: {issue[:120]}\n"
        "+pass\n"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Payload extraction
# ─────────────────────────────────────────────────────────────────────────────

def _extract_fields(payload_raw: str) -> tuple[str, str]:
    """Return (issue_text, search_results)."""
    if not payload_raw or not payload_raw.strip():
        return "", ""
    try:
        p = json.loads(payload_raw)
    except json.JSONDecodeError:
        return payload_raw, ""
    issue = p.get("issue_text") or p.get("issue") or ""
    search = p.get("search_results") or p.get("context") or ""
    return str(issue), str(search) if search else ""


# ─────────────────────────────────────────────────────────────────────────────
# Patch persistence
# ─────────────────────────────────────────────────────────────────────────────

def _save_patch(action_id: Any, patch: str) -> pathlib.Path:
    patch_dir = pathlib.Path(
        os.getenv("DRIFT_PATCH_DIR", "tmp/drift_patches")
    )
    patch_dir.mkdir(parents=True, exist_ok=True)
    p = patch_dir / f"{action_id}.patch"
    p.write_text(patch, encoding="utf-8")
    return p


# ─────────────────────────────────────────────────────────────────────────────
# Main worker loop
# ─────────────────────────────────────────────────────────────────────────────

def run_worker() -> None:
    # Inline import so top-level import errors don't mask env issues
    from asyncaiflow_client import AsyncAiFlowClient, AsyncAiFlowConfig  # type: ignore

    server_url = os.getenv("ASYNCAIFLOW_SERVER_BASE_URL", "http://localhost:8080")
    worker_id = os.getenv("ASYNCAIFLOW_WORKER_ID", "drift-code-worker-py")
    capabilities = [
        cap.strip()
        for cap in os.getenv("ASYNCAIFLOW_CAPABILITIES", ACTION_TYPE).split(",")
        if cap.strip()
    ]
    poll_interval = float(os.getenv("ASYNCAIFLOW_POLL_INTERVAL_SECONDS", "1.0"))

    client = AsyncAiFlowClient(AsyncAiFlowConfig(server_url, worker_id, capabilities))
    client.register_worker()
    logger.info("Registered worker_id=%s capabilities=%s server=%s", worker_id, capabilities, server_url)

    while True:
        try:
            client.heartbeat()
            assignment = client.poll_action()
            if not assignment:
                time.sleep(poll_interval)
                continue

            action_type = assignment.get("type")
            action_id = assignment.get("actionId")
            payload_raw = assignment.get("payload") or ""

            if action_type != ACTION_TYPE:
                client.submit_result(
                    action_id=action_id,
                    status="FAILED",
                    result={"reason": "unsupported action type", "actionType": action_type},
                    error_message=f"unsupported action type: {action_type}",
                )
                continue

            logger.info("Claimed action_id=%s type=%s", action_id, action_type)

            issue, search_results = _extract_fields(payload_raw)
            if not issue:
                client.submit_result(
                    action_id=action_id,
                    status="FAILED",
                    result={"reason": "missing issue_text in payload"},
                    error_message="issue_text is required",
                )
                continue

            try:
                patch = _generate_patch(issue, search_results)
                patch_path = _save_patch(action_id, patch)
                logger.info("action_id=%s patch written to %s (%d bytes)", action_id, patch_path, len(patch))

                client.submit_result(
                    action_id=action_id,
                    status="SUCCEEDED",
                    result={
                        "patch_content": patch,
                        "patch_path": str(patch_path),
                        "lines": len(patch.splitlines()),
                    },
                    error_message=None,
                )

            except Exception as exc:
                logger.exception("Code generation failed for action_id=%s", action_id)
                client.submit_result(
                    action_id=action_id,
                    status="FAILED",
                    result={"error": "code generation failed"},
                    error_message=str(exc),
                )

        except Exception as exc:
            logger.warning("Worker loop error: %s — retrying in %.1fs", exc, poll_interval)
            time.sleep(poll_interval)


if __name__ == "__main__":
    run_worker()
